Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Prgfx.Neos.A11yViews:ImageAlt':
            resource: resource://Prgfx.Neos.A11yViews/Public/ImageAlt/script.js
        stylesheets:
          'Prgfx.Neos.A11yViews:ImageAlt':
            resource: resource://Prgfx.Neos.A11yViews/Public/ImageAlt/styles.css
